# Generated by Django 3.0.6 on 2020-06-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='read',
            field=models.IntegerField(default=0),
        ),
    ]
