# Generated by Django 3.0.6 on 2020-06-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogcomment_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='read',
        ),
        migrations.AddField(
            model_name='post',
            name='read',
            field=models.IntegerField(default=0),
        ),
    ]
